export const brand = {
  name: "Secret Share",
  skip: "Skip to content",
};

export const createCopy = {
  eyebrow: "End-to-end encrypted",
  title: "Share a secret without giving the server the key.",
  lead: "Encryption happens in this browser. The decryption key is stored only in the share link fragment.",
  oneTime: "One-time secrets become unavailable after the first successful reveal.",
  expires: "Expires in 24 hours",
  viewOnce: "Viewed once",
  label: "Secret",
  hint: "A password, API key, or private note. Encrypted on this device before it is stored.",
  submit: "Encrypt and create link",
  submitting: "Encrypting…",
  resultEyebrow: "Ready to share",
  resultTitle: "One-time link",
  resultBody:
    "This link is the only way to decrypt the secret. Copy it now — the server cannot recover it.",
  copyLink: "Copy one-time link",
  copied: "Copied",
  createAnother: "Create another secret",
  error: "Could not create the encrypted share link.",
  signedInHint:
    "You are signed in. This share will appear in your account history as management metadata only. The service cannot recover or redisplay the fragment key or the full link.",
};

export const revealCopy = {
  eyebrow: "One-time secret",
  title: "Reveal this secret",
  beforeReveal: "This secret can be viewed once. After you reveal it, the link stops working.",
  trust: "Decryption happens in this browser. The key stays in the link fragment and is never sent to the server.",
  reveal: "Reveal this secret",
  revealing: "Revealing…",
  secretLabel: "Secret",
  copySecret: "Copy secret",
  copied: "Copied",
  afterReveal: "This secret will not be shown again. Copy it now if you still need it.",
  missingKey: "This link is missing its decryption key.",
  missingKeyHint: "Open the complete share link, including the fragment after #.",
  unavailable: "This secret is unavailable. It may have expired or already been viewed.",
  unavailableTitle: "Secret unavailable",
  decryptFailed: "The secret could not be decrypted. The link may be invalid or modified.",
  decryptFailedTitle: "Could not decrypt",
};

export const chromeCopy = {
  footer: "Client-side AES-256-GCM · Keys stay in the link · Nothing to recover on the server",
  signIn: "Sign in",
  account: "Account",
  signOut: "Sign out",
};

export const accountCopy = {
  eyebrow: "Optional account",
  title: "Share history",
  lead:
    "This page lists management metadata for shares you created while signed in. It is not a recovery inbox. Secret Share never has the URL-fragment decryption key, so it cannot reconstruct or redisplay the complete /s/<id>#k=<key> link.",
  empty: "No owned shares yet. Create a secret while signed in to see its status here.",
  created: "Created",
  expires: "Expires",
  status: "Status",
  revoke: "Revoke",
  revoking: "Revoking…",
  revoked: "Revoked",
  loadMore: "Load more",
  unavailable: "Accounts are not enabled on this deployment.",
  unauthorized: "Sign in to manage shares you created while signed in.",
  error: "Could not load your share history.",
  revokeError: "Could not revoke that share.",
  sessionsTitle: "Active sessions",
  sessionsLead: "Revoke other signed-in sessions if a device is no longer trusted.",
  revokeOthers: "Revoke other sessions",
  signInTitle: "Sign in",
  signUpTitle: "Create an account",
  forgotTitle: "Reset your password",
  verifyTitle: "Check your email",
  resetTitle: "Choose a new password",
  email: "Email",
  password: "Password",
  name: "Name",
  submitSignIn: "Sign in",
  submitSignUp: "Create account",
  submitForgot: "Send reset link",
  submitReset: "Update password",
  genericAuthError: "Could not complete that request. Check the details and try again.",
  verifyLead:
    "If an account exists for that email, a verification link is on its way. Signing in requires a verified address.",
  forgotLead: "If an account exists for that email, a reset link is on its way. This response is the same whether or not the address is registered.",
  resetLead: "Choose a new password. This does not recover any secret-share links.",
  needAccount: "Need an account?",
  haveAccount: "Already have an account?",
  forgotLink: "Forgot password?",
  statusAvailable: "available",
  statusConsumed: "consumed",
  statusExpired: "expired",
  statusRevoked: "revoked",
};
