export const brand = {
  name: "Secret Share",
  skip: "Skip to content",
};

export const createCopy = {
  eyebrow: "End-to-end encrypted",
  title: "Share a secret without giving the server the key.",
  lead: "Encryption happens in this browser. The decryption key is stored only in the share link fragment.",
  oneTime: "One-time secrets become unavailable after the first successful reveal.",
  expires: "Expires in 24 hours",
  viewOnce: "Viewed once",
  label: "Secret",
  hint: "A password, API key, or private note. Encrypted on this device before it is stored.",
  submit: "Encrypt and create link",
  submitting: "Encrypting…",
  resultEyebrow: "Ready to share",
  resultTitle: "One-time link",
  resultBody:
    "This link is the only way to decrypt the secret. Copy it now — the server cannot recover it.",
  copyLink: "Copy one-time link",
  copied: "Copied",
  createAnother: "Create another secret",
  error: "Could not create the encrypted share link.",
};

export const revealCopy = {
  eyebrow: "One-time secret",
  title: "Reveal this secret",
  beforeReveal: "This secret can be viewed once. After you reveal it, the link stops working.",
  trust: "Decryption happens in this browser. The key stays in the link fragment and is never sent to the server.",
  reveal: "Reveal this secret",
  revealing: "Revealing…",
  secretLabel: "Secret",
  copySecret: "Copy secret",
  copied: "Copied",
  afterReveal: "This secret will not be shown again. Copy it now if you still need it.",
  missingKey: "This link is missing its decryption key.",
  missingKeyHint: "Open the complete share link, including the fragment after #.",
  unavailable: "This secret is unavailable. It may have expired or already been viewed.",
  unavailableTitle: "Secret unavailable",
  decryptFailed: "The secret could not be decrypted. The link may be invalid or modified.",
  decryptFailedTitle: "Could not decrypt",
};

export const chromeCopy = {
  footer: "Client-side AES-256-GCM · Keys stay in the link · Nothing to recover on the server",
  signIn: "Sign in",
  signUp: "Create account",
  dashboard: "Dashboard",
  account: "Account",
  signOut: "Sign out",
};

export const accountCopy = {
  signInEyebrow: "Optional account",
  signInTitle: "Sign in to manage shares",
  signInLead: "Signing in never lets the server decrypt a secret. It only attaches management metadata to shares you create while signed in.",
  email: "Email",
  password: "Password",
  name: "Name",
  submitSignIn: "Sign in",
  submitSignUp: "Create account",
  submitting: "Working…",
  genericError: "Unable to complete that request. Check your details and try again.",
  signUpTitle: "Create an account",
  signUpLead: "Accounts are optional. Anonymous sharing still works. We will email a verification link before you can sign in.",
  verifyPending: "Check your email for a verification link. The service cannot recover share-link keys.",
  forgotPassword: "Forgot password",
  resetTitle: "Reset your password",
  resetLead: "If an account exists for that email, we send a reset link. We never reveal whether the email is registered.",
  resetSubmit: "Send reset link",
  resetSent: "If an account exists, a reset link is on its way.",
  newPassword: "New password",
  confirmReset: "Set new password",
  resetDone: "Password updated. Sign in with your new password.",
  verifyTitle: "Verify your email",
  verifyLead: "Open the verification link from your email to activate the account. This does not recover any share links.",
  accountTitle: "Account",
  accountLead: "Sessions are for management only. They cannot reconstruct a one-time link or decrypt a secret.",
  revokeOtherSessions: "Sign out other sessions",
  otherSessionsRevoked: "Other sessions were signed out.",
  signedInAs: "Signed in as",
};

export const dashboardCopy = {
  eyebrow: "Management metadata",
  title: "Your shares",
  lead: "This list is management history only. The server never has the URL-fragment decryption key, so it cannot recover or redisplay the complete /s/<id>#k=<key> link. Copy the full link when you create a share if you still need it.",
  empty: "No account-owned shares yet. Create one while signed in to see its status here.",
  created: "Created",
  expires: "Expires",
  status: "Status",
  revoke: "Revoke",
  revoking: "Revoking…",
  revoked: "Revoked",
  loadMore: "Load more",
  statusAvailable: "available",
  statusConsumed: "consumed",
  statusExpired: "expired",
  statusRevoked: "revoked",
  createHint: "Signed in: this share’s status will appear on your dashboard. The full link is still only shown once.",
};
