CREATE TABLE `user` (`id` text PRIMARY KEY NOT NULL,`name` text NOT NULL,`email` text NOT NULL,`email_verified` integer DEFAULT false NOT NULL,`image` text,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);
CREATE TABLE `session` (`id` text PRIMARY KEY NOT NULL,`user_id` text NOT NULL,`token` text NOT NULL,`expires_at` integer NOT NULL,`ip_address` text,`user_agent` text,`created_at` integer NOT NULL,`updated_at` integer NOT NULL,FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade);
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);
CREATE INDEX `session_user_id_idx` ON `session` (`user_id`);
CREATE TABLE `account` (`id` text PRIMARY KEY NOT NULL,`user_id` text NOT NULL,`account_id` text NOT NULL,`provider_id` text NOT NULL,`access_token` text,`refresh_token` text,`access_token_expires_at` integer,`refresh_token_expires_at` integer,`scope` text,`id_token` text,`password` text,`created_at` integer NOT NULL,`updated_at` integer NOT NULL,FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade);
CREATE INDEX `account_user_id_idx` ON `account` (`user_id`);
CREATE UNIQUE INDEX `account_provider_account_id_uq` ON `account` (`provider_id`,`account_id`);
CREATE TABLE `verification` (`id` text PRIMARY KEY NOT NULL,`identifier` text NOT NULL,`value` text NOT NULL,`expires_at` integer NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
CREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);
CREATE TABLE `secret` (`id` text PRIMARY KEY NOT NULL,`owner_user_id` text,`ciphertext` text NOT NULL,`iv` text NOT NULL,`algorithm` text DEFAULT 'A256GCM' NOT NULL,`created_at` integer NOT NULL,`expires_at` integer NOT NULL,`consumed_at` integer,`delete_after_view` integer DEFAULT true NOT NULL,`version` integer DEFAULT 1 NOT NULL,FOREIGN KEY (`owner_user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null);
CREATE INDEX `secret_expiry_idx` ON `secret` (`expires_at`);
CREATE INDEX `secret_owner_idx` ON `secret` (`owner_user_id`);
